### ISSUE TITLE
Layer switch 

### ISSUE THREAD

**Issue by kirumbatoz** [nawasco/mapboxgljs#1]
we request you to add vector data layer switch to help in switching different layers on and off

**Comment by JinIgarashi** [comment]
as we discussed, we can seperate Mapbox style for sewer network.
- street (water)
- street (sewer)
- satellite (water)
- satellite (sewer)
- unvt (combined both water and sewer)

**Comment by JinIgarashi** [comment]
I fixed. I think now style is bit better. please check
