### ISSUE TITLE
vector layer styles 

### ISSUE THREAD

**Issue by kirumbatoz** [nawasco/mapboxgljs#2]
we request you to change the style color of sewer line from red to green

**Comment by JinIgarashi** [comment]
@kirumbatoz I fixed style of sewer line. I also changed color of blocks boundary from green to red in order to avoid the same color.

**Comment by JinIgarashi** [comment]
@kirumbatoz I changed color of sewerline on satellite from green to orange. Satellite Imagery is mostly using green taste color, it conflicted each other.
